services:
  #  --------------------------------------------
  backend-usermanagment:
    build:
      context: ./userManagment
      dockerfile: Dockerfile
    container_name: container-userManagment
    depends_on:
      mysql-usermanagment:
        condition: service_healthy
    ports:
      - "1115:8080"
    networks:
      - red_microservicios
  #  --------------------------------------------
  mysql-usermanagment:
    build:
      context: ./MySQL
      dockerfile: Dockerfile
    container_name: mysql-usermanagment
    volumes:
      - ./MySQL/mysql_data:/var/lib/mysql
    ports:
      - "1116:3306"
    networks:
      - red_microservicios
    healthcheck:
      test: [ "CMD","mysql", "-u", "finalProject", "-pfinalProject" ]
      interval: 30s
      timeout: 10s
      retries: 5
  #  --------------------------------------------
  adminer-usermanagment:
    image: adminer
    container_name: adminer-usermanagment
    depends_on:
      - mysql-usermanagment
    ports:
      - "1117:8080"
    networks:
      - red_microservicios
#  --------------------------------------------
networks:
  red_microservicios:
    external: true