spring.application.name=userManagment
server.port=8080

# Configuracin de la base de datos MySQL
spring.datasource.url= jdbc:mysql://mysql-usermanagment:3306/finalProject?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=finalProject
spring.datasource.password=finalProject
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracin de Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
# Opciones: create, create-drop, update, validate, none
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en la consola
spring.jpa.show-sql=true
# Formatea la salida SQL
spring.jpa.properties.hibernate.format_sql=true
# Agrega comentarios a las consultas SQL generadas
spring.jpa.properties.hibernate.use_sql_comments=true
# No muestra estadsticas de Hibernate
spring.jpa.properties.hibernate.generate_statistics=false
# Mejora el rendimiento cerrando las sesiones de Hibernate automticamente
spring.jpa.open-in-view=false

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE