FROM mysql:8.0

# Variables de entorno para MySQL
ENV MYSQL_ROOT_PASSWORD=finalProject
ENV MYSQL_DATABASE=finalProject
ENV MYSQL_USER=finalProject
ENV MYSQL_PASSWORD=finalProject

# Exponer el puerto de MySQL
EXPOSE 3306